baseURL = 'https://yingkui.com/'
languageCode = 'en-us'
title = "Yingkui Lin"
theme = "hugo-ink"

copyright = "© Copyright Yingkui.com All Rights Reserved"

[params]
  subtitle = "A Curious Mind."
  avatar = "/logo-ai.jpg"
  customCSS = "css/custom.css"  # Custom CSS applied to default styles.
  mainSections = ['posts']
  math = true

[[menu.main]]
name = "Essays"
url = "/"
weight = 1

[[menu.main]]
name = "Pages"
url = "/pages"
weight = 2

# [[menu.main]]
# name = "MnV"
# url = "/MV"
# weight = 3

# [[menu.main]]
# name = "《教学》"
# url = "/edu"
# weight = 2

# [[menu.main]]
# name = "《人生》"
# url = "/life"
# weight = 3

# [[menu.main]]
# name = "《智力》"
# url = "/ai"
# weight = 4

# [[menu.main]]
# name = "关于"
# url = "/about"
# weight = 8



# [[params.social]]
#     name = "Github"
#     icon = "github"
#     url = "https://github.com/lin"

# # https://feathericons.com/
# [[params.social]]
#     name = "YouTube"
#     icon = "youtube"
#     url = "https://youtube.com/@yingkui"

# [[params.social]]
#     name = "Bluesky"
#     icon = "twitter"
#     url = "https://bsky.app/profile/yingkui.bsky.social"

[permalinks]
  posts = '/:filename'
  pages = '/:filename'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]