baseURL = 'https://albert.cn/'
languageCode = 'en-us'
title = "Output"
theme = "hugo-ink"

copyright = "© Copyright albert.cn All Rights Reserved"

[[menu.main]]
name = "Recent"
url = "/"
weight = 1

[[menu.main]]
name = "Edu"
url = "/edu"
weight = 2

[[menu.main]]
name = "Poems"
url = "/poems"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]
    subtitle = "Albert Yingkui Lin / 林英魁"
    avatar = "/logo-ai.jpg"
    customCSS = "css/custom.css"  # Custom CSS applied to default styles.

[[params.social]]
    name = "Github"
    icon = "github"
    url = "https://github.com/lin"

[permalinks]
  posts = '/:filename'

[markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true