baseURL = 'https://albert.cn/'
languageCode = 'en-us'
title = "Essays"
theme = "hugo-ink"

copyright = "© Copyright Albert Innovation"

[params]
    subtitle = "Albert Yingkui Lin / 林英魁"
    avatar = "/logo-ai.jpg"
    customCSS = "css/custom.css"  # Custom CSS applied to default styles.

[[params.social]]
    name = "Github"
    icon = "github"
    url = "https://github.com/lin"

[permalinks]
  posts = '/:filename'

[markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true