baseURL = 'https://albert.cn/'
languageCode = 'en-us'
title = "Yingkui"
theme = "hugo-ink"

copyright = "© Copyright albert.cn All Rights Reserved"

[[menu.main]]
name = "随想"
url = "/"
weight = 1

[[menu.main]]
name = "教学"
url = "/edu"
weight = 2

[[menu.main]]
name = "人生"
url = "/life"
weight = 3

[[menu.main]]
name = "编程"
url = "/cs"
weight = 4

# [[menu.main]]
# name = "设计"
# url = "/design"
# weight = 3

# [[menu.main]]
# name = "智力"
# url = "/intel"
# weight = 3

# [[menu.main]]
# name = "诗歌"
# url = "/poems"
# weight = 7

[[menu.main]]
name = "关于"
url = "/about"
weight = 8

[params]
    subtitle = "Getting Better. Getting Done."
    avatar = "/logo-ai.jpg"
    customCSS = "css/custom.css"  # Custom CSS applied to default styles.
    mainSections = ['posts']

[[params.social]]
    name = "Github"
    icon = "github"
    url = "https://github.com/lin"

# https://feathericons.com/
[[params.social]]
    name = "YouTube"
    icon = "youtube"
    url = "https://youtube.com/@yingkui"

[permalinks]
  posts = '/:filename'
  notes = '/notes/:filename'

[markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true