# -*- coding: utf-8 -*-
"""Regenerate content/kao/2007年高考绥化一中高三三班成绩与大庆同中考分层考生的对比图.png

This is a static PNG embedded in content/posts/kao.md (not one of the interactive
content/kao/*.html Artifact pages). It must be regenerated by hand whenever
content/kao/2007届绥化一中高三三班中考高考信息.csv changes, since nothing
rebuilds it automatically.

Usage:
    cd scripts
    # 1. Re-extract the current RAW (46-person gk>=600 subset) and DAQING (55-person
    #    Daqing pairs) arrays straight from the interactive artifact's source, so this
    #    static image never drifts from it:
    node -e "
      const fs = require('fs');
      const html = fs.readFileSync('../content/kao/suihua-class3-2007.html', 'utf8');
      const rawM = html.match(/const RAW = (\\[[\\s\\S]*?\\n\\]);/);
      const daqM = html.match(/const DAQING = (\\[[\\s\\S]*?\\n\\]);/);
      fs.writeFileSync('raw.json', JSON.stringify(new Function('return ' + rawM[1])()));
      fs.writeFileSync('daqing.json', JSON.stringify(new Function('return ' + daqM[1])()));
    "
    # 2. Update SLOPE/INTERCEPT/SIGMA and C3_SLOPE/C3_INT/C3_R below if the regression
    #    numbers changed (grep suihua-class3-2007.html for CLASS3_SLOPE/CLASS3_INT/CLASS3_R).
    # 3. Update KNOWN_ORDER/NAMED below if which people count as "已知" changed
    #    (grep the CSV's 高考分数估计依据 column for "已知").
    python3 gen-class3-daqing-png.py
    cp "2007年高考绥化一中高三三班成绩与大庆同中考分层考生的对比图.png" \
       "../content/kao/2007年高考绥化一中高三三班成绩与大庆同中考分层考生的对比图.png"

Design notes:
- Colors/fonts mirror the project's shared token palette used across content/kao/*.html
  (--petrol #0e5b68, --seal #a5342a, --amber #8f5d09, --bar #9aa8ab, --card #f7f9f9).
- The axes use an explicit figure-fraction box (not plt.tight_layout / set_aspect) so
  1 zhongkao point and 1 gaokao point cover the exact same number of pixels — verified
  by the px_per_x == px_per_y sanity check printed at the end.
- Only 林英魁 and 刘翔 are labeled by name (per user instruction); the other 10 people
  whose gaokao score is independently documented ("已知") get a plain 中考X→高考Y label;
  everyone else is an unlabeled hollow red circle. Labels are stacked in the right
  margin with thin leader lines back to their dot, rather than inline, because 12
  labels inline over a cluster this dense overlap unreadably.
- macOS ships "Heiti SC" only as index 1 of the STHeiti Medium.ttc collection; Python's
  fontTools is used to extract that subfont to a standalone HeitiSC.ttf once (see the
  one-time block below) since matplotlib's font manager only reads index 0 ("Heiti TC")
  of a .ttc by default.
"""
import json
import os
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
from matplotlib.patches import Polygon, ConnectionPatch

HERE = os.path.dirname(os.path.abspath(__file__))

# ---- one-time: extract the Simplified-Chinese subfont out of the .ttc collection ----
HEITI_SC = os.path.join(HERE, 'HeitiSC.ttf')
if not os.path.exists(HEITI_SC):
    from fontTools.ttLib import TTCollection
    tc = TTCollection('/System/Library/Fonts/STHeiti Medium.ttc')
    tc.fonts[1].save(HEITI_SC)  # index 1 == "Heiti SC"; index 0 is "Heiti TC"
fm.fontManager.addfont(HEITI_SC)
plt.rcParams['font.sans-serif'] = ['Heiti SC']
plt.rcParams['axes.unicode_minus'] = False

RAW = json.load(open(os.path.join(HERE, 'raw.json'), encoding='utf-8'))
DAQING = json.load(open(os.path.join(HERE, 'daqing.json'), encoding='utf-8'))

SLOPE, INTERCEPT, SIGMA = 0.878, 114.7, 16
C3_SLOPE, C3_INT, C3_R = 1.463, -293.3, 0.79

# 中考成绩估算依据 / 高考分数估计依据 == "已知" 的 12 人（个人身份、去向、分数都独立可查）
KNOWN_ORDER = ['林英魁', '贾洪亮', '刘翔', '梁志超', '王胤燊', '刘雪薇',
               '郭蕾', '陈岩', '李开', '刘欣', '邵润超', '殷旭']
NAMED = {'林英魁', '刘翔'}  # 只有这两人写姓名，其余已知点只标"中考X→高考Y"

PETROL = '#0e5b68'
SEAL = '#a5342a'
AMBER = '#8f5d09'
BAR = '#9aa8ab'
PAPER = '#f7f9f9'
INK = '#0e1416'
INK2 = '#48565a'
INK3 = '#7c8a8e'
HAIR = '#dbe1e1'
RULE = '#c8d0d0'

X0, X1 = 565, 672
Y0, Y1 = 595, 715
XR, YR = X1 - X0, Y1 - Y0

# ---- 手动布局坐标轴的 figure-fraction 框，而不是 set_aspect/tight_layout：
#      保证中考、高考的每一分在图上占同样多像素，且右侧留出空白摆标签 ----
FIG_W, FIG_H = 22, 13.5
AX_BOTTOM, AX_TOP = 0.08, 0.90
AX_HEIGHT = AX_TOP - AX_BOTTOM
ax_h_in = AX_HEIGHT * FIG_H
ax_w_in = ax_h_in * (XR / YR)
AX_LEFT = 0.045
AX_WIDTH = ax_w_in / FIG_W

fig = plt.figure(figsize=(FIG_W, FIG_H))
fig.patch.set_facecolor(PAPER)
ax = fig.add_axes([AX_LEFT, AX_BOTTOM, AX_WIDTH, AX_HEIGHT])
ax.set_facecolor(PAPER)
ax.set_xlim(X0, X1)
ax.set_ylim(Y0, Y1)

for gx in range(570, X1, 10):
    ax.axvline(gx, color=HAIR, lw=1, zorder=0)
for gy in range(600, Y1, 20):
    ax.axhline(gy, color=HAIR, lw=1, zorder=0)


def line(x):
    return SLOPE * x + INTERCEPT


def c3line(x):
    return C3_SLOPE * x + C3_INT


ax.add_patch(Polygon([(X0, line(X0) + SIGMA), (X1, line(X1) + SIGMA),
                       (X1, line(X1) - SIGMA), (X0, line(X0) - SIGMA)],
                      closed=True, facecolor=PETROL, alpha=0.10, edgecolor='none', zorder=1))
ax.plot([X0, X1], [line(X0), line(X1)], color=PETROL, lw=2.4, linestyle=(0, (6, 4)), zorder=2)
ax.plot([X0, X1], [c3line(X0), c3line(X1)], color=SEAL, lw=2.4, linestyle=(0, (6, 4)), zorder=2, alpha=0.9)

ax.text(X0 + 2, Y1 - 6, '大庆回归 · 高考 = 0.878×中考 + 114.7 (r = 0.74)',
        color=PETROL, fontsize=15, fontweight='bold', va='top')
ax.text(X1 - 2, Y0 + 4, f'三班回归 · 高考 ≈ {C3_SLOPE}×中考 + {C3_INT} (r={C3_R})',
        color=SEAL, fontsize=15, fontweight='bold', ha='right', va='bottom')

lm = next(d for d in DAQING if d.get('key'))
for d in DAQING:
    if d.get('key'):
        ax.scatter(d['s'], d['g'], s=90, color=AMBER, edgecolor=PAPER, linewidth=1.2, zorder=4)
    else:
        ax.scatter(d['s'], d['g'], s=46, color=BAR, alpha=0.85, zorder=3)
ax.annotate(f"李梦然  中考 {lm['s']} → 高考 {lm['g']}（全省第 3，清华应届）",
            xy=(lm['s'], lm['g']), xytext=(lm['s'] - 32, lm['g'] - 5),
            fontsize=14, color=AMBER, fontweight='bold', ha='left', va='top',
            arrowprops=dict(arrowstyle='-', color=AMBER, lw=0.9, alpha=0.6), zorder=5)

known_pts = {d['name']: d for d in RAW if d['name'] in KNOWN_ORDER}
for d in RAW:
    if d['name'] in known_pts:
        ax.scatter(d['zhongkao'], d['lo'], s=78, facecolor=SEAL, edgecolor=PAPER, linewidth=1.3, zorder=4)
    else:
        ax.scatter(d['zhongkao'], d['lo'], s=56, facecolor='none', edgecolor=SEAL, linewidth=1.6, alpha=0.8, zorder=3)

ax.set_xticks(range(570, X1, 10))
ax.set_yticks(range(600, Y1, 20))
ax.tick_params(colors=INK3, labelsize=13)
for spine in ax.spines.values():
    spine.set_color(RULE)

ax.text(X0 - 0.10 * XR, Y1 + 0.02 * YR, '2007 高考总分', fontsize=15, color=INK, ha='left')
ax.text(X0 + XR / 2, Y0 - 0.075 * YR,
        '2004 中考分数（大庆考生为实测；三班标出分数的 12 人为已知实分，其余为逐人中考估计分）',
        fontsize=13.5, color=INK2, ha='center')

# ---- 右侧留白：12 个已知点的标签，按高考分降序排一列，用细线连回原点，避免和密集点堆叠冲突 ----
label_pts = sorted(known_pts.values(), key=lambda d: -d['lo'])
n = len(label_pts)
top_y, bot_y = 0.90, 0.10
label_x_fig = AX_LEFT + AX_WIDTH + 0.012
for i, d in enumerate(label_pts):
    name, zk, gk = d['name'], d['zhongkao'], d['lo']
    frac = top_y - (top_y - bot_y) * (i / max(n - 1, 1))
    is_named = name in NAMED
    label = f"{name}  中考 {zk} → 高考 {gk}" if is_named else f"中考 {zk} → 高考 {gk}"
    fig.text(label_x_fig, frac, label, fontsize=14.5 if is_named else 13,
              color=SEAL, fontweight='bold' if is_named else 'normal',
              ha='left', va='center')
    con = ConnectionPatch(xyA=(zk, gk), coordsA=ax.transData,
                           xyB=(label_x_fig - 0.006, frac), coordsB=fig.transFigure,
                           color=SEAL, lw=0.8, alpha=0.55, zorder=2)
    fig.add_artist(con)

OUT = os.path.join(HERE, '2007年高考绥化一中高三三班成绩与大庆同中考分层考生的对比图.png')
fig.savefig(OUT, dpi=150, facecolor=PAPER)

bbox = ax.get_window_extent()
px_per_x = bbox.width / XR
px_per_y = bbox.height / YR
print('px_per_x', px_per_x, 'px_per_y', px_per_y, 'ratio (should be 1.0)', px_per_x / px_per_y)
print('known count =', len(known_pts), '(expect 12)')
print('saved ->', OUT)
